[package]
name = "circle-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
juniper = "0.16.1"
env_logger = "0.11.3"
actix-cors = "0.7.0"
actix-web-lab = "0.20.2"
log = "0.4.21"
serde = "1.0.202"
surrealdb = "1.5.0"
